swagger: "2.0"
info:
  title: Argent Bank transactions API documentation
  description: Contains all available API endpoints for accounts interactions
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
tags:
  - name: accountsModule
    description: Everything about users' accounts
    externalDocs:
      description: Find out more
      url: https://swagger.io
host: localhost:3001
basePath: /api/v1
security:
  - Bearer: []
schemes:
  - http
paths:
  /accounts:
    get:
      security:
        - Bearer: []
      tags:
        - accountsModule
      summary: List of user's accounts
      description: API for fetching the list of accounts of a specific user
      responses:
        "200":
          description: Account list retrieved successully
          schema:
            $ref: "#/definitions/Accounts"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /accounts/{accountID}:
    get:
      security:
        - Bearer: []
      tags:
        - accountsModule
      summary: Key information of a specific account (amout, id, description)
      description: API for fetching a specific account's main info
      parameters:
        - name: accountID
          in: path
          type: string
          description: ID of the account to return
          required: true
      responses:
        "200":
          description: Account info retrieved successully
          schema:
            $ref: "#/definitions/AccountsDetails"
        "400":
          description: Unknown accountID
        "401":
          description: Unauthorized – authentication required
        "500":
          description: Internal Server Error
  /accounts/{accountID}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - accountsModule
      summary: List of transactions for a specific account
      description: API for fetching transactions for an account
      parameters:
        - name: accountID
          in: path
          type: string
          description: ID of the account to return
          required: true
      responses:
        "200":
          description: Account's transactions retrieved successully
          schema:
            $ref: "#/definitions/Transactions"
        "401":
          description: Unauthorized – authentication required
        "404":
          description: No transactions for this account
        "500":
          description: Internal Server Error
  /accounts/{accountID}/transactions/{transactionId}:
    get:
      tags:
        - accountsModule
      summary: Detailed info for a given transaction
      description: API for fetching transaction's details
      parameters:
        - name: accountID
          in: path
          type: string
          description: ID of the account to return
          required: true
        - name: transactionId
          in: path
          type: string
          description: ID of the transaction to return
          required: true
      responses:
        "200":
          description: Transaction's details retrieved successully
          schema:
            $ref: "#/definitions/TransactionDetails"
        "400":
          description: Invalid request body or parameters
        "401":
          description: Unauthorized – authentication required
        "403":
          description: Account does not belong to the user
        "404":
          description: Account not found
        "500":
          description: Internal Server Error
    patch:
      summary: Update transaction details (category and note)
      description: |
        Allows the authenticated user to update the `category` and/or `note` fields
        of a specific transaction associated with one of their accounts.
        Only the provided fields will be updated; other properties remain unchanged.
      tags:
        - accountsModule
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: accountID
          in: path
          type: string
          description: ID of the account to return
          required: true
        - name: transactionId
          in: path
          type: string
          description: ID of the transaction to return
          required: true
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              category:
                type: string
                example: groceries
                description: Updated transaction category
              note:
                type: string
                example: Bought food at the market
                description: Free text note added by the user
      responses:
        "200":
          description: Transaction successfully updated
          schema:
            type: object
            properties:
              id:
                type: string
              type:
                type: string
              category:
                type: string
              note:
                type: string
              updatedAt:
                type: string
                format: date-time
          examples:
            application/json:
              id: "txn123"
              type: "electronic"
              category: "groceries"
              note: "Bought food at the market"
              updatedAt: "2025-05-22T18:00:00Z"
        "400":
          description: Invalid request body or parameters
        "401":
          description: Unauthorized – authentication required
        "403":
          description: Forbidden – transaction does not belong to the user
        "404":
          description: Transaction or account not found
  /transaction/categories:
    get:
      tags:
        - accountsModule
      summary: List of possible categories for a transaction
      description: API for fetching transaction categories
      responses:
        "200":
          description: Transaction categories retrieved successully
          schema:
            $ref: "#/definitions/TransactionsCategories"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
# info bulle sur le cadenas
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
# section "Models"
definitions:
  Accounts:
    type: array
    items:
      $ref: "#/definitions/AccountsDetails"
  AccountsDetails:
    type: object
    properties:
      id:
        type: string
        description: account ID
        example: che1230449949xe
      title:
        type: string
        description: account title
        example: checking account
      amount:
        type: string
        description: amount available
        example: 1800 USD
      description:
        type: string
        description: account description field
        example: current balance
  Transactions:
    type: array
    items:
      $ref: "#/definitions/TransactionDetails"
  TransactionDetails:
    properties:
      id:
        type: string
        description: transaction ID
        example: wire2504659994949
      type:
        type: string
        description: transaction type
        example: transfer
      category:
        type: string
        description: transaction category (from a defined list. ex "housing")
        example: housing
      note:
        type: string
        description: free-text notes added by user, not mandatory
        example: april rent
  TransactionsCategories:
    type: array
    items:
      type: string
      example: groceries
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
            description: account ID
            example: che1230449949xe
          title:
            type: string
            description: account title
            example: checking account
          amount:
            type: string
            description: amount available
            example: 1800 USD
          description:
            type: string
            description: account description field
            example: current balance
